### ISSUE TITLE
Need Help

### ISSUE THREAD

**Issue by lotfiGipsyKing** [kaustubh0mani/BASS-Net#1]
Hello Dear,
So i am a phd student in MASCIR Foundation (Moroccan Foundation for Advanced Science, Innovation & Reserarch) , i work in project of hyperspectrale image classification with Deep Learnig , and search for a large Dataset of hyperspectral image and grounf thruth image , because one image of ground-thruth not enought to make a training in a Deep network , 
i look for your help to find one

**Comment by manila95** [comment]
Hello @lotfiGipsyKing , Sorry to disappoint you but I am not aware of any open source large Hyperspectral Image dataset with ground truth labels. I understand what you are saying but as you can see from the performance of our model. We have trained only on 200 samples per class and tested on the rest, but we are able to get state of the art accuracy, because the problem of less data  per class can be tackled by reducing the number of parameters in your model.

The only problem is that there is no open source dataset available on the web with ground truth labels that has large number of classes.

**Comment by manila95** [comment]
Closing the issue
